# ========================================
# CONFIGURATION WITH LOCATIONS
# ========================================
# This configuration shows the use of location blocks
# for different routes and functionalities

server {
    listen 8082;
    server_name localhost;
    root www;
    index index.html;
    auto_index off;
    error_page 404 /error/404.html;
    location / {
        root www;
        index index.html;
    }
    location /api {
        root www/api;
        index index.html;
        cgi_pass /usr/bin/python3;
        auto_index off;

        error_page 404 /api-404.html;
        error_page 500 /error/500.html;
    }
    location /static/ {
        root www-static;
        auto_index on;
    }
}
